# pipeline

trigger:
- main

pool:
  name: myUbuntuAgentsPool

steps:
- script: source $HOME/python/molecule/bin/activate
  displayName: 'Source molecule'

- script: molecule test
  displayName: 'Run Ansible Test'
