# pipeline

trigger:
- main

pool:
  name: myUbuntuAgentsPool

steps:
- script: source $HOME/python/molecule/bin/activate
  displayName: 'Source molecule'

- script: cd $HOME/iac_poc/iac_poc/roles/ca_directory && molecule test
  displayName: 'Run Ansible Install Test'

- script: cd $HOME/iac_poc/iac_poc/roles/uninstall && molecule test
  displayName: 'Run Ansible Uninstall Test'
