# pipeline

trigger:
- main

pool:
  name: myUbuntuAgentsPool

steps:
- script: cd $HOME/iac_poc/iac_poc/roles && ansible-playbook install-playbook.yml
  displayName: 'Installing CA Directory'

- script: cd $HOME/iac_poc/iac_poc/roles && ansible-playbook verify-install.yml
  displayName: 'Verifying CA Directory Installation'