# pipeline

trigger:
- main

pool:
  name: myUbuntuAgentsPool

steps:
#- script: source $HOME/python/molecule/bin/activate
#  displayName: 'Activate molecule'

- script: cd $HOME/iac_poc/iac_poc/roles/ca_directory && molecule test
  displayName: 'Install CA Directory'

- script: cd $HOME/iac_poc/iac_poc/roles/uninstall && molecule test
  displayName: 'Uninstall CA Directory'
