---
- name: Converge
  hosts: all
  gather_facts: true
  vars_files:
    - /home/iacpocadmin/vault.yml
  tasks:
    - name: "Include iacpoc.ca_directory"
      ansible.builtin.include_role:
        name: "iacpoc.ca_directory"
